language: ruby

# Run cibuild on master branch only
branches:
  only:
    - master

rvm:
  - 2.3.8

# Set execution permission on our build script
before_script:
  - chmod +x ./scripts/cibuild

# Path to our build script. 
# Travis will run `bundle install` by default before running our script
script: ./scripts/cibuild
exclude: [vendor]
sudo: false

